openapi: 3.0.0
info:
  title: Blockchain Interaction API
  version: 1.0.0
paths:
  /blockchain-interaction/balance:
    post:
      summary: Get balance of an address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  example: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e'
      responses:
        '200':
          description: Balance retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
                    example: '1234567890'
  /blockchain-interaction/transaction-count:
    post:
      summary: Get transaction count of an address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  example: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e'
      responses:
        '200':
          description: Transaction count retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
                    example: '42'
  /blockchain-interaction/transaction:
    post:
      summary: Send a transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                  example: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e'
                to:
                  type: string
                  example: '0x53d284357ec70ce289d6d64134dfac8e511c8a3d'
                value:
                  type: string
                  example: '1000000000'
                gas:
                  type: string
                  example: '21000'
                gasPrice:
                  type: string
                  example: '20000000000'
                nonce:
                  type: string
                  example: '1'
      responses:
        '200':
          description: Transaction sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionHash:
                    type: string
                    example: '0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef'

  /token/token-balance:
    post:
      summary: Get token balance of an address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  example: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e'
                privateKey:
                  type: string
                  example: '0x4c0883a69102937d6231471b5dbb6204fe5129617082796e0df1c01f0e7f6fb5'
      responses:
        '200':
          description: Token balance retrieved
          content:
            application/json:
              schema:
                type: string
                example: '1000'
  /token/eth-balance:
    post:
      summary: Get ETH balance of an address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  example: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e'
                privateKey:
                  type: string
                  example: '0x4c0883a69102937d6231471b5dbb6204fe5129617082796e0df1c01f0e7f6fb5'
      responses:
        '200':
          description: ETH balance retrieved
          content:
            application/json:
              schema:
                type: string
                example: '10.5'
  /token/mint:
    post:
      summary: Mint new tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  example: 1000
                privateKey:
                  type: string
                  example: '0x4c0883a69102937d6231471b5dbb6204fe5129617082796e0df1c01f0e7f6fb5'
      responses:
        '200':
          description: Tokens minted
          content:
            application/json:
              schema:
                type: string
                example: '1000'

  /defi/factory-owner:
    get:
      summary: Get the factory owner address
      responses:
        '200':
          description: Factory owner address retrieved
          content:
            application/json:
              schema:
                type: string
                example: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e'
  /defi/enable-fee-amount/{fee}/{tickspacing}:
    get:
      summary: Enable a specific fee amount and tick spacing
      parameters:
        - name: fee
          in: path
          required: true
          schema:
            type: number
            example: 3000
        - name: tickspacing
          in: path
          required: true
          schema:
            type: number
            example: 10
      responses:
        '200':
          description: Fee amount and tick spacing enabled
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
  /defi/tick-spacing/{fee}:
    get:
      summary: Get tick spacing for a given fee
      parameters:
        - name: fee
          in: path
          required: true
          schema:
            type: string
            example: '3000'
      responses:
        '200':
          description: Tick spacing retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  tickSpacing:
                    type: number
                    example: 10
  /defi/create-pool:
    post:
      summary: Create a new liquidity pool
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tokenA:
                  type: string
                  example: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e'
                tokenB:
                  type: string
                  example: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e'
                fee:
                  type: number
                  example: 3000
      responses:
        '200':
          description: Pool created
          content:
            application/json:
              schema:
                type: object
                properties:
                  poolAddress:
                    type: string
                    example: '0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8'
  /defi/pool-address:
    post:
      summary: Get the address of an existing liquidity pool
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tokenA:
                  type: string
                  example: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e'
                tokenB:
                  type: string
                  example: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e'
                fee:
                  type: number
                  example: 3000
      responses:
        '200':
          description: Pool address retrieved
          content:
            application/json:
              schema:
                type: string
                example: '0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8'
